spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}a19e25daa5654ac0e241a7c0dcb0ad94ce4909582183d9416621563f7281743a'

token:
  expiration_time: 86400000
  secret: my-token-application_change_#2

gateway:
  ip: 127.0.0.1
