spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBajYRgQfryhJQ1RU5ADp1dq/+YU15iA6j+mdt6HCH3g8T75Joaq7FhwMnw2fTOwGhWgbPWOC8ChI66fmQ6swfc5W9t4WYNo0TOy9v+Wfy9xApSfY+3GJvL4ruqQ+F1P87KAO/qPx3PHlfMT1d2GyKwq7oIMXsYJVkVWsVLrq3zyX/SM5N6O/9dNbN9F3iJwn7O+ztU6Lyl0qLpqDtMAziTArj0uRHl5+KFjZsskRhVhWJXDnMa6enGCi7AZ6gCEwnEt+NVufi//ytK2dP3hUzj+LsjcJa8JUmcxZdg/qgQPOK02m6b+DQ7IscgTeNvEen+DVPf8ZzQCm2/V96t3rBtZDHGu4qLuCwnXQLFIglKfk/o21oXBot8zDwIdLoyOPc='

token:
  expiration_time: 86400000
  secret: '{cypher}AQA8bHBZxlbAIKfA+jx8lLz6TIudbewlWxtR+zYJSJVM+V7wvuXE4ql+YSnJ6wqw12+qHfj5zMYkvScyCdo/NoKXmHXjlAwDFAnroKIwRCe0uUZ9mKkurpiANgxkYDPDCNYx56JAC5FSD+Ro9BfQg30LGqo0R+OHlxAnyWiy1JcN2x5/eDbjJIvym1O7Bx7PC3P366lbJyGEXEDrPUT1TUXLCnpq2QhJ4s93Q+pzJrUOoMRqGAPO2l/tS4VTunLDjzfPpnwlblZr+qRNPvsAn0vZJZunS8YJs4rkQcLBWrDN234A6U++WWArqnH7QeO35sj2e62yumExRXHgkkntQ7xqC38jy7gxsAnEZ3No3tWWm4fPyiyj9TU3O0RejVcEq7HnKMF6vcJRr/vGxpf0x8YM'

gateway:
  ip: 127.0.0.1
