spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBzhu8WYkOzgcmR6i1N7taOuJXZPlY0GAYYHiXaJzaaWKX8s6FUCyj6A7r2++QjhOKeEwAWIOPOn2zjiAxmLdwPN0xvH9XqXsJHm0dxw02TwEAufi6cXt6I2WhXHc54YDioIIkr4wcLpTTcye2BwryAgsiKmRk7Osb43Vwwrh+r64b/vLIet1fEhJ+EGXj3Yog8MM4AnhLBI3UPlCHoR7tASSWl2iGYZrCVR+wizjQiGGqcQ562YBu9AjVD8t6/4HIxWbRKTJ9o3Gpd2cyYRcWTkJ/HNtBvufddTsWZJ7zQuLmRyQqbEYuEgkEXMajR6x5nfu2kAs/YKFQDitULwDeypWFOTy6+mrfl4eqPvPiXqhKyqWTOYzv8VJMJfPCBTks='

token:
  expiration_time: 86400000
  secret: '{cypher}AQAhHqHx2Mkzc9mKxHyA9FHgN+MtgqlqF+/TQWBRHHdOOTjDohUMc1VqbWqlDXArmlgqmeexmSX/5c3IWb++wR0w/DS/+tYDAnSPd7m09ZCS4sC5QDfrnkSmPj99ci6PvWPVJ8lQm/3mHB1sWc7A3DxmXJEWk3ZAr3vc2ok2nqzPvV85heBmPa9lEA+dtlxtv01OVk1TSwmD66fg+tEsj8mEkd/H3KdlNLMJF39rR2rTr0Z66lvdJJbQVS7SZoVwqANPSuhazCgdzt/lC9UeAcVpYkRwQfQNqg5vR05Gtulpb3ohxVwx/onegazNHv3DV4mwzvWgXy1QBEljaF7ODZLsgNCQds9h2LUX0xPqlrN5g8aGlm3lYCA0IaJWFWVwboGfp+RDi8rG+iEB9GpuSYAq'

gateway:
  ip: 127.0.0.1
